SECURITY.EXCEPTION_CONDITION
    OWNER	    VARCHAR2(20)	N
    TABLE_NAME	VARCHAR2(50)	N
    TYPE	    VARCHAR2(40)	N -- SELECT, UPDATE, INSERT, DELETE, COLUMN 
    CONDITION	VARCHAR2(1000)	N
    ANDOR	    VARCHAR2(200)	Y

SECURITY.EXCEPTION_LOGS
    OWNER	    VARCHAR2(50)	N			
    TABLE_NAME	VARCHAR2(50)	N			
    USER_NAME	VARCHAR2(50)	N			
    TYPES	    VARCHAR2(10)	N			
    LOGTIME	    DATE	        Y			
    TERMINAL	VARCHAR2(50)	Y			
    MODULE	    VARCHAR2(200)	Y			

